# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${APP_DEBUG:-false}'
                XDEBUG_PORT: '${SAIL_XDEBUG_PORT:-9000}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
    postgres:
        image: 'postgres:12'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data/pgdatal'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.7
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
            PGADMIN_DEFAULT_PASSWORD: "root"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        restart: unless-stopped
        networks:
            - sail
        depends_on:
            - postgres
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
